name: editable
description: A highly customizable, editable data table (spreadsheet) package for Flutter projects.
version: 2.0.0
homepage: https://github.com/godilite/editable

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Metric for code quality
  dart_code_metrics: ^4.10.1

    # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^1.0.0

flutter:

  